name       : podofo
version    : 0.9.6
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/podofo/podofo/0.9.6/podofo-0.9.6.tar.gz : e9163650955ab8e4b9532e7aa43b841bac45701f7b0f9b793a98c8ca3ef14072
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : PoDoFo is a library to work with the PDF file format
description: |
    The PoDoFo library is a free, portable C++ library which includes classes to parse PDF files and modify their contents into memory. The changes can be written back to disk easily. The parser can also be used to extract information from a PDF file (for example the parser could be used in a PDF viewer). Besides parsing PoDoFo includes also very simple classes to create your own PDF files. All classes are documented so it is easy to start writing your own application using PoDoFo.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
setup      : |
    %patch -p1 < $pkgfiles/0001-Patch-by-heirecka-Fix-build-with-cmake-3.12.patch
    %cmake -DCMAKE_INSTALL_PREFIX=/usr . \
        -DPODOFO_BUILD_SHARED=1 \
        -DPODOFO_HAVE_JPEG_LIB=1 \
        -DPODOFO_HAVE_PNG_LIB=1 \
        -DPODOFO_HAVE_TIFF_LIB=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
