name       : podofo
version    : 0.9.3
release    : 3
source     :
    - http://sourceforge.net/projects/podofo/files/podofo/0.9.3/podofo-0.9.3.tar.gz/download : ec261e31e89dce45b1a31be61e9c6bb250532e631a02d68ec5bb849ef0a222d8
license    :
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : PoDoFo is a library to work with the PDF file format.
description: |
    The PoDoFo library is a free, portable C++ library which includes classes to parse PDF files and modify their contents into memory. The changes can be written back to disk easily. The parser can also be used to extract information from a PDF file (for example the parser could be used in a PDF viewer). Besides parsing PoDoFo includes also very simple classes to create your own PDF files. All classes are documented so it is easy to start writing your own application using PoDoFo.
builddeps  :
    - libjpeg-turbo-devel
    - pkgconfig(libtiff-4)
    - pkgconfig(libpng)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
setup      : |
    %cmake -DCMAKE_INSTALL_PREFIX=/usr . \
        -DPODOFO_BUILD_SHARED=1 \
        -DPODOFO_HAVE_JPEG_LIB=1 \
        -DPODOFO_HAVE_PNG_LIB=1 \
        -DPODOFO_HAVE_TIFF_LIB=1
build      : |
    %make
install    : |
    %make_install
