name       : podofo
version    : 0.9.8
release    : 12
source     :
    - https://jztkft.dl.sourceforge.net/project/podofo/podofo/0.9.8/podofo-0.9.8.tar.gz : 5de607e15f192b8ad90738300759d88dea0f5ccdce3bf00048a0c932bc645154
homepage   : http://podofo.sourceforge.net/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : PoDoFo is a library to work with the PDF file format
description: |
    The PoDoFo library is a free, portable C++ library which includes classes to parse PDF files and modify their contents into memory. The changes can be written back to disk easily. The parser can also be used to extract information from a PDF file (for example the parser could be used in a PDF viewer). Besides parsing PoDoFo includes also very simple classes to create your own PDF files. All classes are documented so it is easy to start writing your own application using PoDoFo.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
setup      : |
    %cmake -DCMAKE_INSTALL_PREFIX=/usr . \
        -DPODOFO_BUILD_SHARED=1 \
        -DPODOFO_HAVE_JPEG_LIB=1 \
        -DPODOFO_HAVE_PNG_LIB=1 \
        -DPODOFO_HAVE_TIFF_LIB=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
